#!/command/with-contenv sh
# shellcheck shell=sh

if [ "${WSDD2_ENABLE}" != "1" ]; then
  s6-svc -Od .
  exit 0
fi

set --

if [ -n "${WSDD2_HOSTNAME}" ]; then
  set -- "$@" -H "${WSDD2_HOSTNAME}"
fi

if [ -n "${WSDD2_NETBIOS_NAME}" ]; then
  set -- "$@" -N "${WSDD2_NETBIOS_NAME}"
fi

if [ -n "${WSDD2_WORKGROUP}" ]; then
  set -- "$@" -G "${WSDD2_WORKGROUP}"
elif [ -n "${WORKGROUP}" ]; then
  set -- "$@" -G "${WORKGROUP}"
fi

if [ -n "${ALLOWED_INTERFACES}" ]; then
  old_ifs="${IFS}"
  IFS=','
  for iface in ${ALLOWED_INTERFACES}; do
    set -- "$@" -i "${iface}"
  done
  IFS="${old_ifs}"
fi

printf 'Starting wsdd2'
for arg do
  printf ' %s' "${arg}"
done
printf '\n'

exec wsdd2 "$@"
