services:
  samba:
    build: .
    container_name: samba
    restart: unless-stopped
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
      # Required by wsdd2 for Windows network discovery
      - CAP_NET_RAW
    environment:
      TZ: Europe/Warsaw
      SHARE_NAME: public
      WORKGROUP: WORKGROUP
      SERVER_STRING: Home Lab NAS
      FORCE_USER_UID: "1000"
      FORCE_GROUP_GID: "1000"
      # SHARE_DIR_MODE: "0777"
      LOG_LEVEL: "1"
      # SAMBA_PASSWORD: "samba"
      # SAMBA_HOSTS_ALLOW: "192.168.1.0/24 10.13.13.0/24 127.0.0.0/8"
      # WSDD2_ENABLE: "1"
      # WSDD2_HOSTNAME: "homelab"
      # WSDD2_NETBIOS_NAME: "HOMELAB"
      # AVAHI_ENABLE: "1"
      # ALLOWED_INTERFACES: "eno1"
      # FOLLOW_SYMLINKS: "1"
      # GUEST_OK: "1"
    volumes:
      - samba-data:/share

volumes:
  samba-data:
    driver: local
