services:
  samba:
    build: .
    image: local/samba:test
    environment:
      SAMBA_PASSWORD: "test-password"
      LOG_LEVEL: "2"
    volumes:
      - samba-test-data:/share

volumes:
  samba-test-data:
    driver: local
